---
functional:
    - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
    - Пользователь должен иметь возможность фильтровать товары.
    - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
    - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
    - Веб-сайт должен быть разработан с учетом удобства использования.        
    - Сайт должен быть оптимизирован для скорости работы.
    - Сайт должен быть безопасным и защищать данные пользователя.
    - Сайт должен иметь мобильную версию. 
    - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
    - Сайт должен быть способен обрабатывать большое количество графика. 
    - Сайт должен быть доступен на различных устройствах.
implicit:
    - Высокая производительность веб-сайта для быстрой загрузки страниц и обработки запросов.
    - Полная безопасность и конфиденциальность пользовательских данных.
    - Интуитивно понятный интерфейс для повышения удобства использования. 
    - Эффективное управление корзиной товаров и процессом оформления заказа. 
    - Корректное отображение контента и элементов на различных устройствах и браузерах.
    - Надежность и стабильность работы сайта для предотвращения сбоев и недоступности. 
    - Адаптивный дизайн для обеспечения оптимального визуального отображения на разных устройствах. 
    - Доступность сайта для пользователей с ограниченными возможностями (например, с использованием скринридеров или клавиатуры вместо мыши).
